print("Hello world!")
print("Hello again.")
print("I like typing this.")
print("This is fun (right?).")
print('Yay! Printing.')
print("I'd much rather than you 'not'.")
print('I "said" do not touch this.')
